### ISSUE TITLE
Consider text-overflow: ellipsis for long values

### ISSUE THREAD

**Issue by spadgett** [kubernetes-ui/object-describer#16]
We could use style `text-overflow: ellipsis` and then remove the style on click to reveal the full value. This has a few advantages over the `collapse-long-text` directive:
1. Copying the text even if elided will copy the complete value, without needing to expand.
2. The browser will show as much text as it can rather than eliding at some arbitrary character count.
3. The full text will show in a tooltip if the user hovers over it.

/cc @liggitt

**Comment by stefwalter** [comment]
Fixed by #21
